/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BalanceSnapshot {
  asOf: string;
  balance: Numeric;
  clientUpdatedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  reservedAmount: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
  updatedByDevice: string | null;
  version: Generated<Int8>;
}

export interface Category {
  clientUpdatedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  parentId: string | null;
  updatedAt: Generated<Timestamp>;
  updatedByDevice: string | null;
  version: Generated<Int8>;
}

export interface Device {
  clientUpdatedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  memberId: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedByDevice: string | null;
  version: Generated<Int8>;
}

export interface Flow {
  categoryId: string | null;
  clientUpdatedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  dayOfMonth: number | null;
  deletedAt: Timestamp | null;
  direction: string;
  endDate: string | null;
  freq: string | null;
  id: Generated<string>;
  interval: number | null;
  months: number[] | null;
  name: string;
  recurrenceKind: string;
  startDate: string;
  updatedAt: Generated<Timestamp>;
  updatedByDevice: string | null;
  version: Generated<Int8>;
}

export interface FlowAllocation {
  clientUpdatedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  flowId: string;
  id: Generated<string>;
  memberId: string;
  updatedAt: Generated<Timestamp>;
  updatedByDevice: string | null;
  version: Generated<Int8>;
  weight: number;
}

export interface FlowAmount {
  amount: Numeric;
  clientUpdatedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  effectiveFrom: string;
  flowId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedByDevice: string | null;
  version: Generated<Int8>;
}

export interface Goal {
  clientUpdatedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  memberId: string | null;
  name: string;
  priority: Generated<number>;
  savedAmount: Generated<Numeric>;
  targetAmount: Numeric;
  targetDate: string;
  updatedAt: Generated<Timestamp>;
  updatedByDevice: string | null;
  version: Generated<Int8>;
}

export interface Member {
  clientUpdatedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  displayOrder: Generated<number>;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedByDevice: string | null;
  version: Generated<Int8>;
}

export interface Occurrence {
  amount: Numeric;
  clientUpdatedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  dueDate: string;
  flowId: string;
  id: Generated<string>;
  isAmountOverridden: Generated<boolean>;
  isDateOverridden: Generated<boolean>;
  note: string | null;
  ruleDate: string;
  settledAmount: Numeric | null;
  settledOn: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedByDevice: string | null;
  version: Generated<Int8>;
}

export interface SyncState {
  id: Generated<boolean>;
  minRetainedVersion: Generated<Int8>;
}

export interface DB {
  balanceSnapshot: BalanceSnapshot;
  category: Category;
  device: Device;
  flow: Flow;
  flowAllocation: FlowAllocation;
  flowAmount: FlowAmount;
  goal: Goal;
  member: Member;
  occurrence: Occurrence;
  syncState: SyncState;
}
